name: Nightly Fog Check
on:
  schedule:
    # This runs at 23:00 UTC (6:00 PM EST) every day
    - cron: '0 23 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python weather_script.py
